src/ReaderShareProject/Controllers/StaticController.cs
namespace GibixOnline.ReaderShareProject.Controllers {
	#region Using directives

	using System.Web.Mvc;

	#endregion

	/// <summary>
	/// Default static controller for static pages.
	/// </summary>
	public class StaticController : Controller {
		/// <summary>
		/// Default index view.
		/// </summary>
		/// <returns>Returns the default view for this action.</returns>
		public ActionResult Index() { return this.View(); }
	}
}

src/ReaderShareProject/Views/Shared/_Layout.cshtml
@functions {
	MvcHtmlString NavLink(string text, string action, string controller) {
		return new MvcHtmlString("<li><a href=\"{0}\">{1}</a></li>".FormatIC(Url.Action(action, controller), text));
	}
}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>@(String.IsNullOrWhiteSpace(ViewBag.Title) ? "Reader Share Project" : ViewBag.Title + " - Reader Share Project")</title>
	<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/jquery-1.7.1.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>
<body>
	<header>
		<h1>@Html.ActionLink("Reader Share Project", "Index", "Static")</h1>
		<nav>
			<ul>
				@if (this.User.Identity.IsAuthenticated) {
					@NavLink("logout", "Logout", "User")
					@NavLink("posts", "", "Post")
					@NavLink("my account", "Home", "User")
				} else {
					@NavLink("login/create account", "Login", "User")
				}
			</ul>
		</nav>
	</header>
	@if (IsSectionDefined("Submenu")) {
	<ul class="flat-list" id="subnavbar">
		@RenderSection("Submenu")
	</ul>
	}
	<div id="body-content">
	@RenderBody()
	</div>
	<footer>
	</footer>
</body>
</html>