src/ReaderShareProject/Models/User.cs
namespace GibixOnline.ReaderShareProject.Models {
	#region Using directives

	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	#endregion

	/// <summary>
	/// Represents a user in the application.
	/// </summary>
	public class User {
		/// <summary>
		/// Holds the clamed ids for the user.
		/// </summary>
		ICollection<ClaimedId> clamedIds;

		/// <summary>
		/// Holds the friend parings for the user.
		/// </summary>
		ICollection<Friendship> friends;

		/// <summary>
		/// Holds the posts that are owned by the user.
		/// </summary>
		ICollection<Post> posts;

		/// <summary>
		/// Initializes a new instance of the <see cref="User"/> class.
		/// </summary>
		public User() {
			this.Created = DateTime.Now;
			this.LastLoggedIn = DateTime.Now;
		}

		/// <summary>
		/// Gets or sets the date the user was created. [Required]
		/// </summary>
		[Required]
		public DateTime Created { get; set; }

		/// <summary>
		/// Gets or sets the email.
		/// </summary>
		[MaxLength(260)]
		public string Email { get; set; }

		/// <summary>
		/// Gets or sets the email MD5 hash for gravatar.
		/// </summary>
		public Guid EmailMD5 { get; set; }

		/// <summary>
		/// Gets or sets the id. [Key]
		/// </summary>
		[Key]
		public int Id { get; set; }

		/// <summary>
		/// Gets or sets the date the user last logged in. [Required]
		/// </summary>
		[Required]
		public DateTime LastLoggedIn { get; set; }

		/// <summary>
		/// Gets or sets the user's name. [Required]
		/// </summary>
		[Required]
		[MaxLength(100)]
		public string Name { get; set; }

		/// <summary>
		/// Gets or sets the token.
		/// </summary>
		[MaxLength(64)]
		public Guid Token { get; set; }

		/// <summary>
		/// Gets or sets the posting key.
		/// </summary>
		[MaxLength(64)]
		public Guid PostingKey { get; set; }

		/// <summary>
		/// Gets or sets the user's open id authentication URL. [Required]
		/// </summary>
		public virtual ICollection<ClaimedId> ClamedIdentifiers {
			get { return this.clamedIds ?? (this.clamedIds = new List<ClaimedId>()); }
			set { this.clamedIds = value; }
		}

		/// <summary>
		/// Gets or sets the friends of the user.
		/// </summary>
		public virtual ICollection<Friendship> Friends {
			get { return this.friends ?? (this.friends = new List<Friendship>()); }
			set { this.friends = value; }
		}

		/// <summary>
		/// Gets or sets the posts.
		/// </summary>
		public virtual ICollection<Post> Posts {
			get { return this.posts ?? (this.posts = new List<Post>()); }
			set { this.posts = value; }
		}
	}
}

src/ReaderShareProject/Controllers/FeedController.cs
namespace GibixOnline.ReaderShareProject.Controllers {
	#region Using directives

	using System;
	using System.Collections.Generic;
	using System.Data;
	using System.Linq;
	using System.ServiceModel.Syndication;
	using System.Web.Mvc;

	using Dapper;

	using GibixOnline.ReaderShareProject.Models;
	using GibixOnline.ReaderShareProject.Support;

	#endregion

	public class FeedController : BaseController {
		[HttpGet]
		public ActionResult Shares() {
			string formatType = this.RouteData.Values["format"] as string;
			Guid token;
			if (String.IsNullOrWhiteSpace(formatType) || !Guid.TryParse(this.RouteData.Values["token"] as string, out token)) {
				return this.HttpNotFound();
			}

			List<Post> posts = new List<Post>();
			User user;

			using (IDbConnection connection = Engine.GetConnection()) {
				connection.Open();

				var queries = connection.QueryMultiple(
					"SELECT Published, LastUpdated, Title, Summary, OriginalUri OriginalUriString, Content FROM reader.user_feed_view WHERE Token = :Token AND Public = true AND LastUpdated >= :LastUpdated; SELECT EmailMD5, Name, Email FROM reader.users WHERE token = :Token;",
					new {
						Token = token,
						LastUpdated = DateTime.Now.AddMonths(-1)
					});

				posts.AddRange(queries.Read<Post>());
				user = queries.Read<User>().SingleOrDefault();

				connection.Close();
			}

			if (user == null || posts.Count == 0) {
				return this.HttpNotFound();
			}

			List<SyndicationItem> items = new List<SyndicationItem>();
			foreach (Post post in posts.OrderByDescending(p => p.LastUpdated)) {
				SyndicationItem item = new SyndicationItem();
				if (post.OriginalUri != null) {
					item.AddPermalink(post.OriginalUri);
				}

				item.Title = new TextSyndicationContent(post.Title, TextSyndicationContentKind.Plaintext);
				if (!String.IsNullOrWhiteSpace(post.Summary)) {
					Uri uri;
					if (Uri.TryCreate(post.Summary, UriKind.Absolute, out uri)) {
						item.AddPermalink(uri);
					} else {
						item.Content = new TextSyndicationContent(post.Summary, TextSyndicationContentKind.Plaintext);
					}
				}

				if (!String.IsNullOrWhiteSpace(post.Content)) {
					item.Content = new TextSyndicationContent(post.Content, TextSyndicationContentKind.Html);
				}

				items.Add(item);
			}

			SyndicationFeed feed = new SyndicationFeed {
				Copyright = new TextSyndicationContent("All content copyright of their respective owners. This site claims no copyright over the shared content."),
				Description = new TextSyndicationContent("Contains the last month of {0}'s shared items".FormatIC(user.Name), TextSyndicationContentKind.Plaintext),
				Generator = "ReaderShareProject/1.0",
				ImageUrl = new Uri("https://secure.gravatar.com/avatar/{0:n}?s=128".FormatIC(user.EmailMD5)),
				Items = items,
				Language = "en-US",
				LastUpdatedTime = posts.Max(p => p.LastUpdated),
				Title = new TextSyndicationContent("{0}'s shared items".FormatIC(user.Name), TextSyndicationContentKind.Plaintext)
			};
			feed.Authors.Add(new SyndicationPerson(user.Email, user.Name, null));

			if (String.CompareOrdinal(formatType, "atom") == 0) {
				return new AtomActionResult(feed);
			}

			if (String.CompareOrdinal(formatType, "rss") == 0) {
				return new RssActionResult(feed);
			}

			return this.RedirectToAction("Index", "Static");
		}
	}
}

src/ReaderShareProject/Controllers/UserController.cs
namespace GibixOnline.ReaderShareProject.Controllers {
	#region Using directives

	using System;
	using System.Data;
	using System.Linq;
	using System.Web.Mvc;
	using System.Web.Security;

	using Dapper;

	using DotNetOpenAuth.Messaging;
	using DotNetOpenAuth.OpenId;
	using DotNetOpenAuth.OpenId.Extensions.SimpleRegistration;
	using DotNetOpenAuth.OpenId.RelyingParty;

	using GibixOnline.ReaderShareProject.Support;

	#endregion

	/// <summary>
	/// Coordinates actions involving the user objects.
	/// </summary>
	public class UserController : BaseController {
		/// <summary>
		/// Creates a new user account.
		/// </summary>
		/// <param name="name">The user's preferred name.</param>
		/// <param name="email">The user's email address.</param>
		/// <param name="openId">The user's open id.</param>
		/// <returns>An action result.</returns>
		[HttpPost]
		public ActionResult Create(string name, string email, string openId) {
			if (String.IsNullOrWhiteSpace(name) || String.IsNullOrWhiteSpace(email)) {
				this.TempData["CreateError"] = "Missing required data.";
				return this.RedirectToAction("SignUp");
			}

			if (String.CompareOrdinal(this.Session["OpenId"] as string, openId) == 0) {
				using (IDbConnection connection = Engine.GetConnection()) {
					connection.Open();

					using (IDbTransaction transaction = connection.BeginTransaction()) {
						if (connection.Query<int?>("SELECT Id FROM reader.claimed_ids WHERE Identifier = :Identifier", new { Identifier = openId }, transaction).Any()) {
							transaction.Rollback();
							this.TempData["CreateError"] = "Claimed ID already exists.";
							return this.RedirectToAction("SignUp");
						}

						if (connection.Query<int?>("SELECT Id FROM reader.users WHERE UPPER(Email) = :Email", new { Email = email.ToUpperInvariant() }, transaction).Any()) {
							transaction.Rollback();
							this.TempData["CreateError"] = "Email already in use.";
							return this.RedirectToAction("SignUp");
						}

						int? userId = connection.Query<int?>(
							"INSERT INTO reader.users (Email, EmailMD5, Name, Token, PostingKey) VALUES (:Email, :EmailMD5, :Name, :Token, :PostingKey) RETURNING Id",
							new {
								Email = email,
								EmailMD5 = Utilities.MD5Hash(email.Trim().ToLowerInvariant()),
								Name = name,
								Token = Guid.NewGuid(),
								PostingKey = Guid.NewGuid()
							},
							transaction).SingleOrDefault();

						if (userId == null) {
							transaction.Rollback();
							this.TempData["CreateError"] = "Unknown error";
							return this.RedirectToAction("SignUp");
						}

						int? claimedId = connection.Query<int?>(
							"INSERT INTO reader.claimed_ids (Identifier, OwnerId) VALUES (:Identifier, :OwnerId) RETURNING Id",
							new {
								Identifier = openId,
								OwnerId = userId
							},
							transaction).SingleOrDefault();

						if (claimedId == null) {
							transaction.Rollback();
							this.TempData["CreateError"] = "Unknown error";
							return this.RedirectToAction("SignUp");
						}

						transaction.Commit();
					}
				}

				FormsAuthentication.SetAuthCookie(openId, true);
				return this.RedirectToAction("Home");
			}

			return this.RedirectToAction("SignUp");
		}

		[HttpPost]
		public ActionResult Generate(string type) {
			if (this.ReaderUser == null) {
				return this.RedirectToAction("Home");
			}

			if (String.CompareOrdinal(type, "feed") == 0 || String.CompareOrdinal(type, "posting") == 0) {
				using (IDbConnection connection = Engine.GetConnection()) {
					connection.Open();
					connection.Execute(
						"reader.update_user_key(:user_id, :key_type, :new_key)",
						new { user_id = this.ReaderUser.Id, key_type = type, new_key = Guid.NewGuid() },
						commandType: CommandType.StoredProcedure);
					connection.Close();
				}
			}

			return this.RedirectToAction("Home");
		}

		/// <summary>
		/// Returns the home view.
		/// </summary>
		/// <returns>The home view.</returns>
		[HttpGet]
		public ActionResult Home() {
			if (this.ReaderUser == null) {
				return this.RedirectToAction("SignUp");
			}

			using (IDbConnection connection = Engine.GetConnection()) {
				connection.Open();
				ViewBag.PostCount = connection.Query<Int64?>("SELECT COUNT(Id) FROM reader.posts WHERE OwnerId = :OwnerId", new { OwnerId = this.ReaderUser.Id }).SingleOrDefault();
				connection.Close();
			}

			return this.View(this.ReaderUser);
		}

		/// <summary>
		/// Attempts to log the user in via Open ID.
		/// </summary>
		/// <returns>The SignUp view if there the account doesn't exist, the Home view if successful, the login view otherwise.</returns>
		[HttpGet]
		public ActionResult Login() {
			OpenIdRelyingParty party = new OpenIdRelyingParty();
			IAuthenticationResponse response = party.GetResponse();

			if (response != null) {
				switch (response.Status) {
					case AuthenticationStatus.Authenticated:
						int? userId;
						string claimedId = response.ClaimedIdentifier;
						using (IDbConnection connection = Engine.GetConnection()) {
							connection.Open();
							userId = connection.Query<int?>("reader.login_user", new { claimed_id = claimedId }, commandType: CommandType.StoredProcedure).SingleOrDefault();
							connection.Close();
						}

						if (userId == null) {
							ClaimsResponse userData = response.GetExtension<ClaimsResponse>();
							this.TempData["Email"] = userData.Email;
							this.TempData["Name"] = userData.Nickname;
							this.Session["OpenId"] = claimedId;
							return this.RedirectToAction("SignUp");
						}

						FormsAuthentication.SetAuthCookie(claimedId, true);
						return this.RedirectToAction("Home");
				}
			}

			FormsAuthentication.SignOut();
			return this.View();
		}

		/// <summary>
		/// Attempts to log the user in via Open ID.
		/// </summary>
		/// <param name="openId">The open id URL.</param>
		/// <returns>The login view if there is an error or a redirect response to the Open ID provider.</returns>
		[HttpPost]
		public ActionResult Login(string openId) {
			if (String.IsNullOrWhiteSpace(openId) || !Identifier.IsValid(openId)) {
				this.ViewData["Error"] = "The specified login identifier is invalid.";
				return this.View();
			}

			OpenIdRelyingParty party = new OpenIdRelyingParty();
			IAuthenticationRequest request = party.CreateRequest(Identifier.Parse(openId));
			request.AddExtension(new ClaimsRequest { Email = DemandLevel.Require, Nickname = DemandLevel.Request });
			return request.RedirectingResponse.AsActionResult();
		}

		/// <summary>
		/// Logs the user out from forms authentication.
		/// </summary>
		/// <returns>Redirects to the static index view.</returns>
		[HttpGet]
		public ActionResult Logout() {
			FormsAuthentication.SignOut();
			return this.RedirectToAction("Index", "Static");
		}

		/// <summary>
		/// Returns the sign up page.
		/// </summary>
		/// <returns>The sign up page.</returns>
		[HttpGet]
		public ActionResult SignUp() {
			this.ViewData["Email"] = this.TempData["Email"];
			this.ViewData["Name"] = this.TempData["Name"];
			this.ViewData["OpenId"] = this.Session["OpenId"];
			this.ViewData["Error"] = this.TempData["Error"];
			return this.View();
		}
	}
}

src/ReaderShareProject/Views/User/Home.cshtml
@model GibixOnline.ReaderShareProject.Models.User
@{
	ViewBag.Title = "Home";
}

<img src="https://secure.gravatar.com/avatar/@this.Model.EmailMD5.ToString("n")?s=128" alt="gravatar" height="128" width="128" style="float: left;" />
<div style="float: left; margin-left: 1em;">
<h2>Welcome @Model.Name!</h2>
<p>
	Since you joined @Model.Created.ToString("d") you have shared a total of @ViewBag.PostCount item@(ViewBag.PostCount == 1 ? String.Empty : "s") to your friends.
</p>
<h3>Sharing articles</h3>
@using (Html.BeginForm("Generate", "User", new { type = "feed" }, FormMethod.Post, new { @id = "feed-key" })) {
<p>
	To allow any of your friends to view your shares, you will need to give them your special feed URL.<br />
	Your current feed key is: @Model.Token.ToString("n").<br />
	We recommend using the atom feed for sharing with Google Reader users.
</p>
<p>
	Want to hide from your friends? You can <a href="#" onclick="document.getElementById('feed-key').submit(); return false;" title="Generate a new posting key">generate a new feed key</a> so the old URL will no longer be valid.<br />
	If you do this, you will need to tell your friends to update to the new URL.
</p>
}
<p>
	@Html.ActionLink("Atom 1.0", "Shares", "Feed", new { token = this.Model.Token.ToString("n"), format = "atom" }, null) | @Html.ActionLink("RSS 2.0", "Shares", "Feed", new { token = this.Model.Token.ToString("n"), format = "rss" }, null)<br />
</p>
<h3>Posting articles</h3>
@using (Html.BeginForm("Generate", "User", new { type = "posting" }, FormMethod.Post, new { @id = "posting-key" })) {
<p>
	To quickly post an article from Google Reader you need to set up Reader Share Project as a Send To destination. <br />
	Your current posting key is: @Model.PostingKey.ToString("n").<br />
	If you think your posting key was compromised you can <a href="#" onclick="document.getElementById('posting-key').submit(); return false;" title="Generate a new posting key">generate a new posting key</a>.
</p>
}
<p>
	Keeping your posting key private is very important. If someone gets your posting key, they can submit articles in your name without needing to<br />
	log in as you. If this does happen, just generate a new key. None of your existing data will be at risk if your key is compromised. If you<br />
	generate a new posting key, you will need to update your <strong>Send To</strong> link in Google Reader.
</p>
<h4>Creating a <em>Send To</em> link in Google Reader</h4>
<ol>
	<li>Sign in to <a href="http://www.google.com/reader" title="Google Reader" rel="external">Google Reader</a> and open up the Reader Settings.</li>
	<li>Click on the <strong>Send To</strong> tab.</li>
	<li>In the <strong>Don't see your favorite site?</strong> section click the <em>"Create a custom link"</em> link.</li>
	<li>
		Fill out the form with the following data:<br />
		<table>
			<tbody>
				<tr>
					<th>Name</th>
					<td>Reader Share Project</td>
				</tr>
				<tr>
					<th>URL</th>
					<td>@Request.Url.Scheme://@Request.Url.Authority/post/@Model.PostingKey.ToString("n")/share?source=${source}&amp;title=${title}&amp;url=${url}</td>
				</tr>
				<tr>
					<th>Icon URL</th>
					<td>@Request.Url.Scheme://@Request.Url.Authority/feed.png</td>
				</tr>
			</tbody>
		</table>
	</li>
</ol>
</div>

src/ReaderShareProject/Views/User/Login.cshtml
@model GibixOnline.ReaderShareProject.Models.User
@{ ViewBag.Title = "Login"; }

<div class="center width50">
@using (Html.BeginForm("Login", "User", FormMethod.Post, new { @id = "login" })) {	
	@Html.ValidationSummary(true)
	<p>This site uses OpenID to authenticate our users. This allows you to use your own trusted provider and we
	never see your password.</p>
	<p>If you have never used this site before you will be directed to the account creation page after successful authentication.</p>
	<table class="form">
		<tfoot>
			<tr>
				<td colspan="2"><input type="submit" value="Continue" /></td>
			</tr>
		</tfoot>
		<tbody>
			@if (!String.IsNullOrWhiteSpace(this.ViewBag.Error)) {
			<tr><td colspan="2">@ViewBag.Error</td></tr>
			}
			<tr>
				<th>
					<label for="openId">Open ID URL:</label><br />
					<span>Please enter your Open ID URL.</span>
				</th>
				<td>
					<div><input type="url" value="" name="openId" id="openId" size="30" /></div>
				</td>
			</tr>
			<tr>
				<th></th>
				<td>
					<button type="button" onclick="openid.login('google');">Google</button>
					<button type="button" onclick="openid.login('yahoo');">Yahoo!</button>
					<button type="button" onclick="openid.login('myopenid');">myOpenID</button>
				</td>
			</tr>
		</tbody>
	</table>
}
</div>
<script type="text/javascript">
	//<![CDATA[
	var openid = {};
	(function (jQuery) {
		var $ = jQuery,
			login = $("#login"),
			providers = {
				google: "https://www.google.com/accounts/o8/id",
				myopenid: "http://myopenid.com/",
				yahoo: "http://yahoo.com/"
			},
			url = $("#openId");

		this.login = function (provider) {
			url.val(providers[provider]);
			login.submit();
		};
	}).call(openid, window.jQuery);
	//]]>
</script>

src/ReaderShareProject/Views/User/SignUp.cshtml
@model GibixOnline.ReaderShareProject.Models.User
@{ ViewBag.Title = "Create a new account"; }

<div class="center width50">
<p>By creating an account, you are agreeing to the <a href="#/static/terms_of_service">terms of service</a>. @*<strong>Remember that this site is open to web crawlers, so people will be able to easily search your name.</strong>*@</p>
@using (Html.BeginForm("Create", "User")) {
	@Html.Hidden("openid", ViewData["OpenId"])
	@Html.ValidationSummary(true)	
	<table class="form">
		<tfoot>
			<tr>
				<td colspan="2"><input type="submit" value="Sign up" /></td>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<th style="width: 35%;">
					@Html.LabelFor(m => m.Name, "Name:")
					<span>Can be whatever you want, can't change it after (yet).</span>
				</th>
				<td style="width: 85%;">
					<div>@Html.TextBoxFor(m => m.Name, new { size = "30", @Value = ViewData["Name"] })</div>
					@Html.ValidationMessageFor(m => m.Name)
				</td>
			</tr>
			<tr>
				<th>
					@Html.LabelFor(m => m.Email, "Email:")
					<span>Required, used to merge open id accounts (eventually).</span>
				</th>
				<td>
					<div>@Html.TextBoxFor(m => m.Email, new { type = "email", size = "30", @Value = ViewData["Email"] })</div>
				</td>
			</tr>
		</tbody>
	</table>
}
</div>